all:
	gcc -c hw0501.c
	gcc -c rotate.c
	gcc hw0501.o rotate.o -o hw0501 -lm
	gcc -c hw0502.c
	gcc -c mymemcmp.c
	gcc hw0502.o mymemcmp.o -o hw0502
	gcc hw0503.c -o hw0503
	gcc -c hw0504.c division.c
	gcc hw0504.o division.o -o hw0504