all:
	gcc -c hw0301.c myfunc.c
	gcc hw0301.o myfunc.o -o hw0301
	gcc -c hw0302.c mystddev.c
	gcc hw0302.o mystddev.o -o hw0302 -lm
	gcc -c hw0303.c resistance.c
	gcc hw0303.o resistance.o -o hw0303
	gcc -c hw0304-1.c hanoi.c
	gcc hw0304-1.o hanoi.o -o hw0304-1 -lm
	gcc -c hw0304-2.c hanoi.c
	gcc hw0304-2.o hanoi.o -o hw0304-2 -lm
	gcc -c hw0305.c logic.c smallten.c
	gcc hw0305.o logic.o smallten.o -o hw0305